spring:
  kafka:
    bootstrap-servers: localhost:9092

  main:
    allow-bean-definition-overriding: true


  data:
    mongodb:
      host: localhost
      port: 27017
      database: crud
      username: root
      password: example
      authentication-database: admin

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/crud
    username: root
    password: example

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

kafka:
  topic:
    success: successful_logs
    error: error_logs
    paymentLog: payment_log
    paymentProcess: payment_process

  groupId: groupId

